import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import { CartProvider } from "./_context/cart";
import OpenCart from "./_components/open-cart";
import AuthProvider from "./provider/auth-provider";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "auto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={`antialiased`}>
        <AuthProvider>
          <CartProvider>
            {children}
            <Toaster />
            <OpenCart />
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
